version: '3.8'

services:

  function:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    depends_on:
      - placement
    networks:
      - dummy-dapr

  function-dapr:
    image: "daprio/daprd:edge"
    command: [
      "./daprd",
     "-app-id", "function",
     "-placement-host-address", "placement:50000",
     "-resources-path", "./components",
     "-log-level", "debug"
     ]
    volumes:
      - ~/.dapr/components:/components
    depends_on:
      - function
    network_mode: "service:function"

  placement:
    image: "daprio/dapr"
    command: ["./placement", "--port", "50000"]
    ports:
      - "50000:50000"
    volumes:
      - ~/.dapr:/root/.dapr
    networks:
      - dummy-dapr
    environment:
      - DAPR_LOG_LEVEL=debug
      - DAPR_METRICS_PORT=9090

  redis:                                                                          
    image: "redis"
    hostname: "redis"
    ports:
      - "6379:6379"
    networks:
      - dummy-dapr

networks:
  dummy-dapr: null